apiVersion: apps/v1
kind: Deployment

metadata:
  labels:
    app: ProjApp
  name: ProjApp

spec:
  replicas: 3
  selector:
    matchLabels:
      app: ProjApp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ProjApp

    spec:
      containers:
      - image: ammarabdelhady8132/pipeline-test
        name: pipeline-test
        resources: {}
status: {}
